workspace:
  base: /go
  path: src/github.com/honestbee/drone-chartmuseum

pipeline:
  prepare:
    image: golang:1.10-alpine
    commands:
    - apk add --update --no-cache git curl
    - curl -fsSL -o dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 
    - chmod +x dep
    - curl -fsSL -o cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - chmod +x ./cc-test-reporter

  test:
    image: golang:1.10-alpine
    secrets: 
    - cc_test_reporter_id
    commands:
    - apk add --update --no-cache git
    - ./dep ensure
    - ./cc-test-reporter before-build
    - go test -coverprofile c.out ./...
    - ./cc-test-reporter after-build

  docker-build:
    image: plugins/docker
    repo: quay.io/honestbee/drone-chartmuseum
    tags: 
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - latest
    registry: quay.io
    email: "devops@honestbee.com"
    secrets: [ docker_username, docker_password ]
    when:
      branch: [ master ]

  notify:
    image: plugins/slack
    channel: feed-devops
    secrets: 
      - source: slack_webhook
        target: plugin_webhook
    when:
      status: [ success, failure ]
